### ISSUE TITLE
Vue Not Rendering

### ISSUE THREAD

**Issue by boldstar** [sadnub/laravel-tenancy-passport-demo#1]
Alright so everything as far as registering and logging in works.

So once logged in it calls the home view
```
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Ticketing System</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts anf CSS -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css" rel="stylesheet">

</head>
<body>
    <div id="app">

    </div>
</body>
</html>
```
Here is the app.blade.php
```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.js"></script>

    <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons' rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">   

</head>
<body>
    <div id="app">
        <v-app>
            <v-content>
                <v-container>
                    @yield('content')
                </v-container>
            </v-content>
        </v-app>
    </div>

    <script>
      new Vue({ el: '#app' })
    </script>
  
</body>
</html>
```

Here is the app.js set up
```
import Vue from 'vue'
import VueRouter from 'vue-router'
import Vuetify from 'vuetify'
import App from '@/App'
import routes from '@/routes.js'

//Load Plugins
Vue.use(VueRouter)
Vue.use(Vuetify)

//Router configuration
const router = new VueRouter({
    routes 
  })

new Vue({
    el: '#app',
    router,
    render: h => h(App),
});
```
*note that `const = app` is not needed so I removed it

I also changed the folder structure to match yours

[click here](https://imgur.com/a/gYtdeMS) to view the folder structure image. I don't know how to directly paste the image.

**Comment by sadnub** [comment]
@boldstar Try running `npm install `and `npm run dev` in the laravel base directory. This should build the modules. Thanks for the tip about `const app =` I removed it.

**Comment by boldstar** [comment]
@sadnub, after running `npm run dev` this is the warnings I get. Originally I wass getting errors which I corrected however at this point it is still not rendering the vue components. 
```
 WARNING  Compiled with 3 warnings                                 14:49:48
 warning  in ./resources/assets/js/app.js

28:17-20 "export 'default' (imported as 'App') was not found in '@/App'

 warning  in ./resources/assets/js/App.js

28:17-20 "export 'default' (imported as 'App') was not found in '@/App'

 warning  in ./resources/assets/js/App.js

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\laragon\www\tenancytest\node_modules\babel-loader\lib\index.js??ref--4-0!C:\laragon\www\tenancytest\resources\assets\js\App.js
    Used by 2 module(s), i. e.
    C:\laragon\www\tenancytest\node_modules\babel-loader\lib\index.js??ref--4-0!C:\laragon\www\tenancytest\resources\assets\js\app.js
* C:\laragon\www\tenancytest\node_modules\babel-loader\lib\index.js??ref--4-0!C:\laragon\www\tenancytest\resources\assets\js\app.js
    Used by 1 module(s), i. e.
    multi C:\laragon\www\tenancytest\resources\assets\js\app.js
                                                                   Asset    Size  Chunks                    Chunk Names
/js/app.js  1.4 MB       0  [emitted]  [big]  /js/app

WARNING in ./resources/assets/js/app.js
28:17-20 "export 'default' (imported as 'App') was not found in '@/App'
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js

WARNING in ./resources/assets/js/App.js
28:17-20 "export 'default' (imported as 'App') was not found in '@/App'
 @ ./resources/assets/js/App.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js

WARNING in ./resources/assets/js/App.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\laragon\www\tenancytest\node_modules\babel-loader\lib\index.js??ref--4-0!C:\laragon\www\tenancytest\resources\assets\js\App.js
    Used by 2 module(s), i. e.
    C:\laragon\www\tenancytest\node_modules\babel-loader\lib\index.js??ref--4-0!C:\laragon\www\tenancytest\resources\assets\js\app.js
* C:\laragon\www\tenancytest\node_modules\babel-loader\lib\index.js??ref--4-0!C:\laragon\www\tenancytest\resources\assets\js\app.js
    Used by 1 module(s), i. e.
    multi C:\laragon\www\tenancytest\resources\assets\js\app.js
 @ ./resources/assets/js/App.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js
```

**Comment by sadnub** [comment]
Is App.js supposed to be named App.vue? It looks like it is trying to import that but it isn't a module.

**Comment by boldstar** [comment]
So after some thinking I changed App.vue too AppView.vue. Basically the errors were because the naming convention of App.vue and app.js are to similar. 

I now show a successful build
```
 Size  Chunks                    Chunk Names
/js/app.js  1.4 MB       0  [emitted]  [big]  /js/app
```
Oddly though i am still not getting the components showing up Lol

**Comment by sadnub** [comment]
Are you importing AppView in app.js? You may need to change the render function below

```
new Vue({
    el: '#app',
    router,
    render: h => h(AppView),
});
```

**Comment by boldstar** [comment]
@sadnub , yes I did change that. the issue was I had removed 'id="app" from my `div` in the home.blade.php file. It works like a charm now Lol

**Comment by boldstar** [comment]
Now my goal is to abstract the login process to my API. One thing I have noticed about this set up is we are using the `LoginController` which Is completely different from how I am currently logging in over api. I have to use passport with this method in a custom controller
```
$guzzle = new GuzzleHttp\Client;

$response = $guzzle->post('http://your-app.com/oauth/token', [
    'form_params' => [
        'grant_type' => 'client_credentials',
        'client_id' => 'client-id',
        'client_secret' => 'client-secret',
        'scope' => 'your-scope',
    ],
]);

return json_decode((string) $response->getBody(), true)['access_token'];
```

Here are the [docs from laravel](https://laravel.com/docs/5.7/passport#creating-a-personal-access-client) where this method comes from. I guess because  the user needs personal access token it needs to be done this way.

I just am not sure how to incorporate multi-tenant with this process. @sadnub, any ideas?

**Comment by sadnub** [comment]
I'm a little confused on your setup. From what I understand, you have an Auth API separate from the Laravel API. The Laravel API serves your Vue app. You want your login logic to be in the Laravel API that connects to the Auth API. Does that sound right?

**Comment by boldstar** [comment]
sorry for the long post in advance lol

@sadnub , yeah so you have the login route set up in the web.php file, where as I am using it in the api.php file. So for instance you are only calling the tickets by api, I am making all of my calls in the api.php file. So when I call the login route from Vue app it goes some thing like this

My vue app store.js sends a post request
```
axios.post('/login', {
  username: username,
  password: password
})
.then(response => {
  //do something
})
.catch(error => {
// do something
})
```
the laravel api.php has the /login route
```
Route::post('/login', 'AuthController@login');
```

AuthController is a custom controller. Inside there is where I have the login method
```
public function login(Request $request)
    {
        $http = new \GuzzleHttp\Client;
        try {
            $response = $http->post(config('services.passport.login_endpoint'), [
                'form_params' => [
                    'grant_type' => 'password',
                    'client_id' => config('services.passport.client_id'),
                    'client_secret' => config('services.passport.client_secret'),
                    'username' => $request->username,
                    'password' => $request->password,
                ]
            ]);
            return $response->getBody();
        } catch (\GuzzleHttp\Exception\BadResponseException $e) {
            if ($e->getCode() === 400) {
                return response()->json('Invalid Request. Please enter a username or a password.', $e->getCode());
            } else if ($e->getCode() === 401) {
                return response()->json('Your credentials are incorrect. Please try again', $e->getCode());
            }
            return response()->json('Something went wrong on the server.', $e->getCode());
        }
    }
```
the `client_id` and `client_secret` are generated by passport when you run the command `passport:install`. So in the `form_params` I have those variables stored in the .env file. so that when I make a login request from the front end it hits my /oauth/token endpoint to generate a access_token which if credentials are correct will be sent back to the user and they will be logged in.

which is a little different from how we are logging in with this passport demo. So what I want to be able to do  is register a new tenant myself on the backend and then provide credentials for them to log in with...

The workflow I am essentially trying to achieve is this
1. I register a new tenant on the backend
2. A database is created for that tenants instance
3. I provide the new tenant with credentials to login with
4. when they login to the fqdn for them it only shows them there data

**Comment by sadnub** [comment]
For the authentication piece, you might be looking for something like this.
https://medium.com/@joelbrubaker/laravel-passport-spa-frontend-authentication-e876cd81928f

In addition to that article, you would need to get a client ID and client secret per tenant. Or you could store your client IDs in the system database. You can run `php artisan passport:install` from the controller also and it will create the keys.

Unfortunately, I don't have too much experience implementing that myself

**Comment by boldstar** [comment]
@sadnub , yeah I see that we are already calling the `php artisan passort:install` command inside the `Tenant` model at line 45 which is called by the register controller when adding a new tenant.
```
Artisan::call('passport:install')
```
So I guess at that point I would need to insert the created passport keys into the system database with maybe the `tenant_id` as a foreign key?

**Comment by sadnub** [comment]
That will create your client id and client secret on a per-tenant basis. You could create tenant specific config files (named something like passport.php) and save the client ID and secret there. See below:
https://laravel-tenancy.com/docs/hyn/5.3/structure

Then in your controller, you can query them from the config(passport.client_id) and it will pull the client ID for the specific tenant based on the hostname used.

You will need to write the config files during registration. But that should definitely work.

**Comment by boldstar** [comment]
@sadnub , so I have hit a snag in developing my version of the multi-tenant setup with passport and I was wondering if maybe you would have some insight!!

instead of writing out  my issue again I will link the discussion below
[CLICK HERE](https://laracasts.com/discuss/channels/laravel/how-to-dynamically-call-passport-login-end-pointoauthtoken)

essentially I am having an issue with passport login endpoint 'oauth/token' that passport uses to create access_tokens...

Obviously no rush but if you get a chance to look at it, I would be thrilled. Thanks! Lol

**Comment by sadnub** [comment]
@boldstar I'm not sure why that isn't working. I haven't set anything up like that before.

However, I am refactoring my login/register pages so that Laravel is only serving my index.blade.php file. VueJS will be building my register/login pages, but I will still be using web auth in them. Once I get that working I will report back on how that goes.

Web Auth, in my opinion, is the way to go. The API auth seems more difficult to implement and maintain and I read there can be security concerns.

**Comment by sadnub** [comment]
@boldstar I might have this working. Try this in your LoginController

```
protected function authenticated(Request $request, $user)
    {
        return Response::json($user, 200)
            ->withCookie($this->cookieFactory->make(
                $user->getKey(), $request->session()->token()
            ));
    }
```

Move your login routes to the web.php.

In my Vue setup I have something like this.

auth.js (Import into your components)
```
import axios from '@/config/axios.js'

export default {

	getToken() {
		let token = document.head.querySelector('meta[name="csrf-token"]')
		return token.content
	},
	
	login(data) {
		return axios.post('/login', data)
	},

	logout() {
		return axios.post('/logout')
	},

	register(data) {
		return axios.post('/register', data)
	}
}
```

And my Login Component (with Vuetify)

```
<template>
	<v-layout align-center justify-center>
    <v-flex xs12 sm8 md4>
      <v-card class="elevation-12">
        <v-toolbar dark color="primary">
          <v-toolbar-title>Login form</v-toolbar-title>
        </v-toolbar>
        <v-card-text>
          <v-form @submit.prevent="submit">
            <input type="hidden" name="_token" :value="token">
            <v-text-field 
              prepend-icon="person" 
              v-model="credentials.email" 
              name="email" 
              label="Email" 
              type="text"></v-text-field>
            <v-text-field 
              prepend-icon="lock" 
              v-model="credentials.password" 
              name="password" 
              label="Password" 
              type="password"></v-text-field>
            <v-checkbox
              label="Remember Me"
              name="remember"
              v-model="remember"
            ></v-checkbox>
          </v-form>

          <v-card-actions>
            <router-link :to="{ name: 'password.email' }">
              Forgot Your Password
            </router-link>
            <v-spacer></v-spacer>
            <v-btn @click="submit" color="primary">Login</v-btn>
          </v-card-actions>
        </v-card-text>
      </v-card>
    </v-flex>
  </v-layout>
</template>

<script>

import Auth from '@/api/auth.js'

export default {

  data: () => ({
    credentials: {
      email: '',
      password: '',
      remember: false
    }
  }),

  computed: {
    token() { return Auth.getToken() }
  },

  methods: {
    submit() {
      Auth.login(this.credentials)
      .then(response => {
        this.$router.push('/dashboard')
      })
      .catch(error => {
        console.log(error)
      })
    }
  }

}
</script>
```

So this is leveraging web auth using Ajax. There are no loading indicators so you may want to show a message or a loading icon.

I'm still working through this, but this is what I have so far. Maybe I'll write a followup article once I have a finished solution.

Hope this helps!

**Comment by sadnub** [comment]
@boldstar This is what I came up with for the Laravel Auth integration with VueJS. Hope this helps!

https://medium.com/@sadnub/vuejs-and-laravel-auth-part-2-5-d7c9d0263226
