### ISSUE TITLE
SOLVED: Send registration Failed

### ISSUE THREAD

**Issue by AlphaJosh** [sadnub/laravel-tenancy-passport-demo#3]
Sorry, I am a Laravel Noob

I have run ./vendor/bin/phpunit and it is all successful except for the following, what am I doing wrong sorry:

Feature\Auth\Registration
 ✘ Send registration
   │
   │ Expected status code 201 but received 500.
   │ Failed asserting that false is true.
   │
   │ /var/www/onroad/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:133
   │ /var/www/onroad/tests/Feature/Auth/RegistrationTest.php:36

**Comment by AlphaJosh** [comment]
The solution was to comment out a line in App/Tenant.php :

app(Connection::class)->statement("SET GLOBAL validate_password_policy=LOW");

**Comment by sadnub** [comment]
@AlphaJosh Thanks for letting me know! I'll check into that.

**Comment by sadnub** [comment]
@AlphaJosh See #4 You should be able to clone the Main branch and everything will work.
Thanks!
